---
name: Labeler

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  issues:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  labeler:
    uses: DevSecNinja/.github/.github/workflows/labeler.yml@0d0f448de257f354c89dc3a128871235d6ba8c11 # v2.5.0
    permissions:
      contents: read
      issues: write # Apply labels to newly opened or edited issues.
      pull-requests: write # Apply labels to same-repository PRs.
    with:
      config-path: pr-labeler.yaml
      issue-config-path: issue-labeler.yaml
