---
name: Label Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
      - .github/labels-base.yaml
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  label-sync:
    uses: DevSecNinja/.github/.github/workflows/label-sync.yml@0d0f448de257f354c89dc3a128871235d6ba8c11 # v2.5.0
    permissions:
      contents: read
      issues: write # Create, update, and remove repository labels.
    with:
      base-labels-file: .github/labels-base.yaml
      labels-file: .github/labels.yaml
      delete-other-labels: true
